name: Validate HACS repository

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  validate-appdaemon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate AppDaemon
        uses: hacs/action@main
        with:
          category: "appdaemon"

  validate-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Integration
        uses: hacs/action@main
        with:
          category: "integration"
          ignore: "brands"
